#!/bin/bash
# cool_gpu       This script will enable or disable fixed gpu fan speed 
#
# chkconfig: 345 95 5
# description:  A script hack for GPU fan control on headless GPU nodes
#

# Copyright (c)2011, Axel Kohlmeyer <akohlmey@gmail.com>

# locations of all the magic
dir=/home/dan/set-gpu-fans
smi=/usr/bin/nvidia-smi
set=/usr/bin/nvidia-settings

${smi} -pm 1

# for multiple tesla devices, only one display is supported.
# thus we need to launch the X server once for each display
# making each of the PCI IDs the primary device in turn.

# command to set fan speed on primary GPU.
FAN_PCT=100
nvscmd="${set} -a [gpu:0]/GPUFanControlState=1 -a [fan:0]/GPUTargetFanSpeed=${FAN_PCT}"

# go back to automatic, if called with stop argument
if [ "x$1" == "xstop" ]
then
  # with the newer driver, going back to default
  # is simple. we just turn off persistence mode
  # and trigger one reset by showing the GPU status
  ${smi} -pm 0
  ${smi}
  exit 0
fi

# get PCI bus ids of Nvidia cards and convert from hexadecimal to decimal. watch out for the falling toothpicks.
pciid=`lspci  | sed -n -e '/VGA compatib.*NVIDIA/s/^\(..\):\(..\).\(.\).*/printf "PCI:%d:%d:%d\\\\\\\\n" 0x\1 0x\2 0x\3;/p'`

for s in `eval ${pciid}`
do \
    cfg=`mktemp /tmp/xorg-XXXXXXXX.conf`
    sed -e s,@GPU_BUS_ID@,${s},    \
        -e s,@SET_GPU_DIR@,${dir}, \
        ${dir}/xorg2.conf >> ${cfg}
    xinit ${nvscmd} --  :0 -once -config ${cfg}
    rm -f ${cfg}
done

